modmap:
  - name: Swap Left Super/Alt
    device:
      not: ['ZSA Technology Labs ErgoDox EZ', 'Input:Club Infinity Ergodox (QMK)']
    remap:
      CapsLock: Ctrl_L

default_mode: default
keymap:
  - name: Pass-through to KDE
    remap:
      # Switch workspace
      Super-Shift-a: Super-a
      # Display selection
      Super-Shift-p: Super-p
      # Lock
      Super-Shift-l: Super-l
      # Toggle Tiles editor
      Super-Shift-t: Super-t
      # Toggle Battery performance
      Super-Shift-b: Super-b
      # Toggle grid view
      Super-Shift-g: Super-g
      # Screenshoft
      Super-Shift-s: Super-shift-s
      # Toogle Overview
      Super-Shift-w: Super-shift-w
      # Show Clipboard Items
      Super-Shift-v: Super-v

  - name: Mac-Super-Bindings
    remap:
      Super-a: Ctrl-a
      Super-tab: Alt-tab
      Super-c: C-c
      Super-z: C-z
      Super-x: C-x
      Super-l: C-l
      Super-f: C-f
      Super-w: C-w
      Super-t: C-t
      Super-r: C-r
      Super-n: C-n
      Super-p: C-p
      Super-s: C-s
      Super-q: Alt-F4
      Super-b: C-b
      Super-k: C-k
  - name: Mac-Super-V-in-terminal
    application:
      only: ['Alacritty']
    remap:
      Super-v: Paste
      Super-c: Copy
  - name: Mac-Super-V-in-other
    application:
      not: ['Alacritty']
    remap:
      Super-v: C-v
  - name: Mac-Ctrl-Bindings
    application:
      not: ['konsole', 'Konsole', 'alacritty', 'Alacritty']
    window:
      not: ['konsole', 'Konsole', 'alacritty', 'Alacritty', 'tmux']
    remap:
      ctrl-n: Down
      ctrl-p: Up
      ctrl-a: Home
      ctrl-e: End
      ctrl-d: Delete
      ctrl-k: [Shift-End, Delete]
